### ISSUE TITLE
Extras / Import -- Bug + proposed solution

### ISSUE THREAD

**Issue by vlc33** [Rayquaza01/authenticator#19]
Hello I use Extra / Export to get my topt.json, it works.

But then I delete all entries and try to get Extra / Import of the saved file, but nothing happens I have to retype all entries mannually.

I just examined the topts.json file and found a solution replacing a regex as follows
`/,"fontColor":"$/}/`

It works but the solution inside the code I do not know how to do it.

Thank You.

Please fill out this information:
 * Browser version: Latest FIrefox PC 63.0.3
 * Extension version: 1.2.1
 * Operating system: Windows 10

**Comment by Rayquaza01** [comment]
Hello,
Thank you for pointing this out. It's the same issue in Rayquaza01/note-taker#18

So, a data URL is used to create the export. The URL looks something like `data:application/json;charset=utf-8,{"fontColor":"#000000"}`. If you open that URL, you'll see `SyntaxError: JSON.parse: unterminated string literal at line 1 column 15 of the JSON data`. This is because `#` causes data URLs to end early. This can be fixed by running `encodeURIComponent` on the export data to get a URL like `data:application/json;charset=utf-8,%7B"fontColor"%3A"%23000000"%7D`, which will work correctly.

**Comment by Rayquaza01** [comment]
Fixed in 1.3.1
