### ISSUE TITLE
Window still needs to be scrolled

### ISSUE THREAD

**Issue by Silergo** [Rayquaza01/authenticator#3]
This bug https://github.com/Rayquaza01/authenticator/issues/1 still present in 1.0.4 version.
![2fa](https://user-images.githubusercontent.com/32046715/30526551-cface062-9c24-11e7-8d13-b60126c837ce.png)
**Firefox 55.0.3 (64-bit)**

**Comment by Rayquaza01** [comment]
This is actually something different from #1. When a key is unable to be processed, it breaks the loop and stops loading the ones listed below it. It's likely that your third one is entered incorrectly somehow. Make sure that it's a valid key and that you didn't mistype it.

There definitely should be visual indication of when errors occur in future versions.

**Comment by Silergo** [comment]
You were right. The third one is wex (former btce), after deleting this it shows the last one. But I definetly input it right. Maybe it's something with the key format? Can I send it to you?

**Comment by Rayquaza01** [comment]
I've never used wex before and it seems to behave a bit strange. On the 2fa page, make sure you use the "Base32 Private Key" instead of just "Private Key". If wex tells you "Invalid password" when you enter the code, hit cancel and try again with the new key it generates. In my testing, only every other secret key it generates actually works with the extension. I have no idea why, I'll have to look into it more.

**Comment by Silergo** [comment]
Ok, now it's work after I insert "=" at the end of the secret key Oo. Which is strange, because as I remember I did this before and it doesn't show. The key that was generate accepted with the first time and no need to generate another one. I guess you can close this one.
