### ISSUE TITLE
How do I move my Authenticator config from one FF profile to another?

### ISSUE THREAD

**Issue by xpseudonym** [Rayquaza01/authenticator#38]
## Question

Hello, Thank you for Authenticator - I do so like not having to rely on my beep'ing phone!

I've moved my gnu/linux flavour and Firefox has installed itself to a new profile in the process - so, how do I import my config for Authenticator so I can continue to login to my various.

I've moved my <profile>/browser-extension-data/authenticator@r01 without effect - but it was empty anyway.

Many thanks.

**Comment by Rayquaza01** [comment]
Hello,
By far the easiest way would be to use the Import and Export buttons on the extension's options page. If you still have the entire profile from your old `~/.mozilla/firefox`, you can move that profile to `~/.mozilla/firefox` and launch that profile from `about:profiles` (or by running `firefox -P -no-remote`). You may need to add an entry to `profiles.ini`. Then you can export your data from the options page in the old profile and import it to your new profile.

By the way, `/browser-extension-data` hasn't been used for storing extension data since 2018 (https://blog.mozilla.org/addons/2018/08/03/new-backend-for-storage-local-api/). WebExtensions use IndexedDB, but I'm not entirely sure where on disk the extension data is stored.

**Comment by xpseudonym** [comment]
Hi Ray (I assume that's correct?)

Thanks for that - just had to think about it a different way...

With the upgraded Authenticator I'm asked for a password before authentication codes are revealed - that's okay, but - and it's a big BUT - the password is revealed in clear text in the toolbar icon!!!  That's not the case in the Add-on preferences where the password entry is hidden.  Should I report this as a bug or am I missing something to ensure passwords are hidden?
Thanks
Morgan.

**Comment by Rayquaza01** [comment]
The password being in plain text is because of #16 and #23. There was a bug in Firefox on linux that caused the popup to immediately close when a password field was focused. I'm reopening #23 because it seems I never actually changed the text field back to a password field.

**Comment by xpseudonym** [comment]
Thanks.
